import type { ITheme } from '@xterm/xterm'

export interface TerminalTheme {
  id: string
  label: string
  category: 'dark' | 'light'
  theme: ITheme
}

/**
 * 终端主题预设列表。
 * 每个主题的 `theme` 字段对应 xterm.js ITheme 接口。
 */
export const terminalThemes: TerminalTheme[] = [
  {
    id: 'default',
    label: '跟随应用',
    category: 'dark',
    theme: {
      background: '#0A0A0A',
      foreground: '#A3A3A3',
      cursor: '#E5E5E5',
      selectionBackground: '#0070f3',
      selectionForeground: '#0A0A0A',
      black: '#333333',
      red: '#EF4444',
      green: '#22C55E',
      yellow: '#f5a623',
      blue: '#0070f3',
      magenta: '#eb367f',
      cyan: '#50e3c2',
      white: '#A3A3A3',
      brightBlack: '#525252',
      brightRed: '#EF4444',
      brightGreen: '#22C55E',
      brightYellow: '#f5a623',
      brightBlue: '#3291ff',
      brightMagenta: '#eb367f',
      brightCyan: '#50e3c2',
      brightWhite: '#EDEDED',
    },
  },
  {
    id: 'midnight',
    label: '午夜纯黑',
    category: 'dark',
    theme: {
      background: '#000000',
      foreground: '#B0B0B0',
      cursor: '#FFFFFF',
      selectionBackground: '#264F78',
      selectionForeground: '#FFFFFF',
      black: '#000000',
      red: '#CD3131',
      green: '#0DBC79',
      yellow: '#E5E510',
      blue: '#2472C8',
      magenta: '#BC3FBC',
      cyan: '#11A8CD',
      white: '#E5E5E5',
      brightBlack: '#666666',
      brightRed: '#F14C4C',
      brightGreen: '#23D18B',
      brightYellow: '#F5F543',
      brightBlue: '#3B8EEA',
      brightMagenta: '#D670D6',
      brightCyan: '#29B8DB',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'solarized-dark',
    label: 'Solarized Dark',
    category: 'dark',
    theme: {
      background: '#002B36',
      foreground: '#839496',
      cursor: '#93A1A1',
      selectionBackground: '#073642',
      selectionForeground: '#93A1A1',
      black: '#073642',
      red: '#DC322F',
      green: '#859900',
      yellow: '#B58900',
      blue: '#268BD2',
      magenta: '#D33682',
      cyan: '#2AA198',
      white: '#EEE8D5',
      brightBlack: '#586E75',
      brightRed: '#CB4B16',
      brightGreen: '#586E75',
      brightYellow: '#657B83',
      brightBlue: '#839496',
      brightMagenta: '#6C71C4',
      brightCyan: '#93A1A1',
      brightWhite: '#FDF6E3',
    },
  },
  {
    id: 'nord',
    label: 'Nord',
    category: 'dark',
    theme: {
      background: '#2E3440',
      foreground: '#D8DEE9',
      cursor: '#D8DEE9',
      selectionBackground: '#434C5E',
      selectionForeground: '#D8DEE9',
      black: '#3B4252',
      red: '#BF616A',
      green: '#A3BE8C',
      yellow: '#EBCB8B',
      blue: '#81A1C1',
      magenta: '#B48EAD',
      cyan: '#88C0D0',
      white: '#E5E9F0',
      brightBlack: '#4C566A',
      brightRed: '#BF616A',
      brightGreen: '#A3BE8C',
      brightYellow: '#EBCB8B',
      brightBlue: '#81A1C1',
      brightMagenta: '#B48EAD',
      brightCyan: '#8FBCBB',
      brightWhite: '#ECEFF4',
    },
  },
  {
    id: 'dracula',
    label: 'Dracula',
    category: 'dark',
    theme: {
      background: '#282A36',
      foreground: '#F8F8F2',
      cursor: '#F8F8F2',
      selectionBackground: '#44475A',
      selectionForeground: '#F8F8F2',
      black: '#21222C',
      red: '#FF5555',
      green: '#50FA7B',
      yellow: '#F1FA8C',
      blue: '#BD93F9',
      magenta: '#FF79C6',
      cyan: '#8BE9FD',
      white: '#F8F8F2',
      brightBlack: '#6272A4',
      brightRed: '#FF6E6E',
      brightGreen: '#69FF94',
      brightYellow: '#FFFFA5',
      brightBlue: '#D6ACFF',
      brightMagenta: '#FF92DF',
      brightCyan: '#A4FFFF',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'one-dark',
    label: 'One Dark',
    category: 'dark',
    theme: {
      background: '#282C34',
      foreground: '#ABB2BF',
      cursor: '#528BFF',
      selectionBackground: '#3E4451',
      selectionForeground: '#ABB2BF',
      black: '#282C34',
      red: '#E06C75',
      green: '#98C379',
      yellow: '#E5C07B',
      blue: '#61AFEF',
      magenta: '#C678DD',
      cyan: '#56B6C2',
      white: '#ABB2BF',
      brightBlack: '#5C6370',
      brightRed: '#E06C75',
      brightGreen: '#98C379',
      brightYellow: '#E5C07B',
      brightBlue: '#61AFEF',
      brightMagenta: '#C678DD',
      brightCyan: '#56B6C2',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'gruvbox',
    label: 'Gruvbox Dark',
    category: 'dark',
    theme: {
      background: '#282828',
      foreground: '#EBDBB2',
      cursor: '#EBDBB2',
      selectionBackground: '#504945',
      selectionForeground: '#EBDBB2',
      black: '#282828',
      red: '#CC241D',
      green: '#98971A',
      yellow: '#D79921',
      blue: '#458588',
      magenta: '#B16286',
      cyan: '#689D6A',
      white: '#A89984',
      brightBlack: '#928374',
      brightRed: '#FB4934',
      brightGreen: '#B8BB26',
      brightYellow: '#FABD2F',
      brightBlue: '#83A598',
      brightMagenta: '#D3869B',
      brightCyan: '#8EC07C',
      brightWhite: '#EBDBB2',
    },
  },
  {
    id: 'tokyo-night',
    label: 'Tokyo Night',
    category: 'dark',
    theme: {
      background: '#1A1B26',
      foreground: '#A9B1D6',
      cursor: '#C0CAF5',
      selectionBackground: '#33467C',
      selectionForeground: '#A9B1D6',
      black: '#15161E',
      red: '#F7768E',
      green: '#9ECE6A',
      yellow: '#E0AF68',
      blue: '#7AA2F7',
      magenta: '#BB9AF7',
      cyan: '#7DCFFF',
      white: '#A9B1D6',
      brightBlack: '#414868',
      brightRed: '#F7768E',
      brightGreen: '#9ECE6A',
      brightYellow: '#E0AF68',
      brightBlue: '#7AA2F7',
      brightMagenta: '#BB9AF7',
      brightCyan: '#7DCFFF',
      brightWhite: '#C0CAF5',
    },
  },
  // ── 浅色主题 ──
  {
    id: 'solarized-light',
    label: 'Solarized Light',
    category: 'light',
    theme: {
      background: '#FDF6E3',
      foreground: '#657B83',
      cursor: '#657B83',
      selectionBackground: '#EEE8D5',
      selectionForeground: '#657B83',
      black: '#073642',
      red: '#DC322F',
      green: '#859900',
      yellow: '#B58900',
      blue: '#268BD2',
      magenta: '#D33682',
      cyan: '#2AA198',
      white: '#EEE8D5',
      brightBlack: '#586E75',
      brightRed: '#CB4B16',
      brightGreen: '#586E75',
      brightYellow: '#657B83',
      brightBlue: '#839496',
      brightMagenta: '#6C71C4',
      brightCyan: '#93A1A1',
      brightWhite: '#002B36',
    },
  },
  {
    id: 'one-light',
    label: 'One Light',
    category: 'light',
    theme: {
      background: '#FAFAFA',
      foreground: '#383A42',
      cursor: '#383A42',
      selectionBackground: '#E5E5E6',
      selectionForeground: '#383A42',
      black: '#383A42',
      red: '#E45649',
      green: '#50A14F',
      yellow: '#C18401',
      blue: '#4078F2',
      magenta: '#A626A4',
      cyan: '#0184BC',
      white: '#A0A1A7',
      brightBlack: '#4F525E',
      brightRed: '#DF6C75',
      brightGreen: '#98C379',
      brightYellow: '#E4C07A',
      brightBlue: '#61AFEF',
      brightMagenta: '#C577DD',
      brightCyan: '#56B6C2',
      brightWhite: '#FFFFFF',
    },
  },
  {
    id: 'gruvbox-light',
    label: 'Gruvbox Light',
    category: 'light',
    theme: {
      background: '#FBF1C7',
      foreground: '#3C3836',
      cursor: '#3C3836',
      selectionBackground: '#D5C4A1',
      selectionForeground: '#3C3836',
      black: '#FBF1C7',
      red: '#CC241D',
      green: '#98971A',
      yellow: '#D79921',
      blue: '#458588',
      magenta: '#B16286',
      cyan: '#689D6A',
      white: '#7C6F64',
      brightBlack: '#928374',
      brightRed: '#9D0006',
      brightGreen: '#79740E',
      brightYellow: '#B57614',
      brightBlue: '#076678',
      brightMagenta: '#8F3F71',
      brightCyan: '#427B58',
      brightWhite: '#3C3836',
    },
  },
  {
    id: 'ayu-light',
    label: 'Ayu Light',
    category: 'light',
    theme: {
      background: '#FAFAFA',
      foreground: '#575F66',
      cursor: '#FF9940',
      selectionBackground: '#F0F0F0',
      selectionForeground: '#575F66',
      black: '#000000',
      red: '#F51818',
      green: '#86B300',
      yellow: '#F2AE49',
      blue: '#399EE6',
      magenta: '#A37ACC',
      cyan: '#4CBF99',
      white: '#FAFAFA',
      brightBlack: '#000000',
      brightRed: '#F51818',
      brightGreen: '#86B300',
      brightYellow: '#F2AE49',
      brightBlue: '#399EE6',
      brightMagenta: '#A37ACC',
      brightCyan: '#4CBF99',
      brightWhite: '#FAFAFA',
    },
  },
]

/** 根据 id 获取主题，找不到则返回默认主题 */
export function getTerminalTheme(id: string): ITheme {
  return terminalThemes.find((t) => t.id === id)?.theme ?? terminalThemes[0].theme
}

/** 获取主题元信息（包含背景色与分类） */
export function getTerminalThemeMeta(id: string): TerminalTheme {
  return terminalThemes.find((t) => t.id === id) ?? terminalThemes[0]
}

/**
 * 'default' 主题跟随应用深浅色：深色用默认深色盘，浅色自动切 one-light
 * （与应用浅色 chrome 同源的极简浅色盘）。显式选择的主题保持固定。
 */
export function resolveTerminalThemeId(id: string, appTheme: 'light' | 'dark'): string {
  if (id !== 'default') return id
  return appTheme === 'light' ? 'one-light' : 'default'
}
